### ISSUE TITLE
How should isla-preprocess be used? (Read kind Read_ifetch does not exist in supplied architecture)

### ISSUE THREAD

**Issue by Trolldemorted** [rems-project/isla#11]
With the container from #10 I can compile sail-arm (extended by a function that initializes PSTATE) into the ir:
```
isla-sail_1  | [WARNING] Running as root is not recommended
isla-sail_1  | Type check [==================================================] 100% (10746/10746)
isla-sail_1  | Rewrite [==================================================] 100% (initial)
isla-sail_1  | Rewrite [==================================================] 100% (initial)
isla-sail_1  | Type check [==================================================] 100% (8811/8811)
isla-sail_1  | Rewrite [==================================================] 100% (properties)
isla-sail_1  | Specializing [==================================================] 100% (vector_update_B)
isla-sail_1  | Type check [==================================================] 100% (8933/8933)
isla-sail_1  | Rewriting [==================================================] 100% (vector_update_B)
isla-sail_1  | Type check [==================================================] 100% (8933/8933)
isla-sail_1  | Specializing [==================================================] 100% (zz7azJzK0#eq_anyt...)
isla-sail_1  | Type check [==================================================] 100% (8272/8272)
isla-sail_1  | Rewriting [==================================================] 100% (zz7azJzK0#eq_anyt...)
====================================] 100% (3/3)
isla-sail_1  | Compiling [==================================================] 100% (initialize_registers)
====================================] 100% (3/3)
```

but isla-preprocess can't convert that ir into the irx and symtab:
```
PS C:\Users\Benni\repositories\isla_orig> cargo run --bin isla-preprocess -- -A C:\Users\Benni\repositories\master-arm\aarch64\aarch64.ir -o C:\Users\Benni\repositories\master-arm\aarch64
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target\debug\isla-preprocess.exe -A C:\Users\Benni\repositories\master-arm\aarch64\aarch64.ir -o C:\Users\Benni\repositories\master-arm\aarch64`
Read kind Read_ifetch does not exist in supplied architecture
error: process didn't exit successfully: `target\debug\isla-preprocess.exe -A C:\Users\Benni\repositories\master-arm\aarch64\aarch64.ir -o C:\Users\Benni\repositories\master-arm\aarch64` (exit code: 1)
```

If I invoke isla-preprocess with `-C .\configs\aarch64.toml` I get the same error. What am I doing wrong? Do I have to rename things in the sail model before invoking isla-sail, or change the line `ifetch = "Read_ifetch"` in your config tomls? Iirc I didn't have this problem when preprocessing your snapshots.

**Comment by Alasdair** [comment]
Hmm it should exist. I'm not sure what is going on. It's defined here: https://github.com/rems-project/sail/blob/sail2/lib/regfp.sail and the ARM spec shouldn't build without it. It's only included in the read kinds if ARM_SPEC is set, as we only have relaxed memory instruction fetch semantics for ARM so far.

Are you building using the symbolic branch of the sail-arm repository?

**Comment by Trolldemorted** [comment]
I was building the default branch (master), I have now tried symbolic, but isla-sail can't build the ir:

```
PS C:\Users\Benni\repositories\master-arm\sail-arm> docker-compose up isla-sail
Recreating master-arm_isla-sail_1 ... done
Attaching to master-arm_isla-sail_1
isla-sail_1  | Type error:[===                                               ] 6% (791/11321)
isla-sail_1  | [/model/aarch_types.sail]:46:5-12
isla-sail_1  | 46 |enum boolean = {FALSE, TRUE}
isla-sail_1  |    |     ^-----^
isla-sail_1  |    | Cannot create enum boolean, type name is already bound
isla-sail_1  |    | 
master-arm_isla-sail_1 exited with code 1
```

If you merge https://github.com/rems-project/sail/issues/107 I can set up CI for the sail -> ir -> irx chain, so regressions don't go unnoticed.

**Comment by Alasdair** [comment]
Hmm, I don't have that problem. boolean isn't a reserved keyword in sail (bool is) and it should only be defined once in aarch_types.sail in the sail-arm repo.

It's kind of pointless because our translator from ASL knows to replace uses of that enum with the actual sail bool type, so in practice I think that type definition could just be deleted.

**Comment by Trolldemorted** [comment]
Aah my bad, I passed one file twice, so the error message made sense!

So I can build the symbolic branch to ir and that to irx&symtab, will it replace master in the future, or should I worry about my problems with master?

**Comment by Alasdair** [comment]
I will probably keep the two branches separate: the master branch serves as a direct translation from ASL, whereas the symbolic branch has a bunch of manual tweaks I made to make it more amenable to symbolic execution. For isla, the symbolic branch is the one you should be using.

For example, to make the concurrency semantics work properly, more information needs to propagated down to the lowest level memory primitives than what occurs in the ARM ASL so I had to do that by hand. Another type of change I did was modify how the NZCV flags were set so they didn't cause a path explosion every time they were set.

**Comment by Trolldemorted** [comment]
Makes sense, but you might want to document that somewhere (or have the CI build from that branch so users will realize it themselves)
