### ISSUE TITLE
Should Ty have copy semantics?

### ISSUE THREAD

**Issue by Trolldemorted** [rems-project/isla#19]
In #18 I have put several `Ty`s behind Arcs because you have been using them behind references at some places, but the enum feels like a copy type, since `Ty<Name>` is the variant used most often (only `Ty<String>` appears to be used in some other places).

**Comment by Alasdair** [comment]
It's not copy because clone because of the recursive enum variants that contain `Box<Ty<A>>`. Cloning (and therefore copying) makes a deep copy of the recursive structure.
