### ISSUE TITLE
Dependency versions in isla-lib are overwritten by Cargo.lock (and it fails to build)

### ISSUE THREAD

**Issue by Trolldemorted** [rems-project/isla#25]
Your isla-lib toml specifies these dependencies:

https://github.com/rems-project/isla/blob/15ecd0f2c75d9dfc61736566c68f0c366bcf4262/isla-lib/Cargo.toml#L20-L31

Your Cargo.lock file however specifies different versions:
```
[[package]]
name = "regex"
version = "1.3.7"
```
```
[[package]]
name = "toml"
version = "0.5.6"
```
```
[[package]]
name = "libc"
version = "0.2.69"
```
```
[[package]]
name = "serde"
version = "1.0.106"
```

So if you build isla-lib from within the isla project, it will pull the versions from your Cargo.lock (serde v1.0.106), but if you depend on isla-lib in a project which is not a subproject of isla, it will pull other versions (serde v1.0.118, currently the latest). I think in no circumstance it will pull the dependency defined in isla-lib's Cargo.toml (serde 1.0.104).

Because of this your CI has not noticed that isla-lib currently fails to build if you depend on it from a project which is not in this repository (serde had an API breaking change between minor versions):
```
error: cannot find derive macro `Serialize` in this scope
```
(caused by https://github.com/serde-rs/serde/issues/1586)

**Comment by Alasdair** [comment]
Should be fixed now. As far as I know cargo will use the latest semver compatible version to whatever is in the Cargo.toml file. My understanding is that convention dictates that executables have Cargo.lock checked in, but it should remain uncommitted for libraries:

https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by Trolldemorted** [comment]
Cargo's behaviour was unexpected for me too, because the semver in isla-lib's toml did not allow that upgrade - imho it shoud at least throw unambigious warnings, and not silently violate the requirements.

Multi-package projects are special because direct dependencies must be the same version across all packages in a project, but in my case cargo chose neither the version specified in the toml, nor the one specified in the lock. Do you agree that this looks like a cargo bug?

I know about that convention, but what are multi-package projects like isla supposed to do?

**Comment by Alasdair** [comment]
Probably we should have always had the `derive` feature specified, so it's our bug. The version string "1.0.104"  in a Cargo file is equivalent to ">=1.0.104, <2.0.0", so what it did is allowed. It's not a cargo bug if upstream projects do accidentally break semver guarantees.

For multi-package projects you can use Cargo workspaces (which we do use) so everything shares the same lockfile and build directory. We could add a cargo update to our CI system to try to catch issues like this.

**Comment by Trolldemorted** [comment]
>The version string "1.0.104" in a Cargo file is equivalent to ">=1.0.104, <2.0.0"

Oh you are right, the cargo spec says "no prefix means caret prefix" (who thought this was a good idea? o_O), so cargo indeed behaves as expected.
