### ISSUE TITLE
Tool riscv64-linux-gnu-as not found in $PATH

### ISSUE THREAD

**Issue by fengwz17** [rems-project/isla#42]
I run isla-footprint on ubuntu 20.04, but face such an error, I am confused that how to install riscv64-linux-gnu-as, since I can only install riscv64-unknown-linux-gnu or riscv64-unknown-elf  from https://github.com/riscv-collab/riscv-gnu-toolchain

**Comment by bacam** [comment]
It's in the binutils-riscv64-linux-gnu Ubuntu package.

**Comment by Alasdair** [comment]
The path to the various RISC-V tools are set by the configuration file. I know different Linux distros have slightly different names for some of these binaries, so you may need to change the configuration, as I set up the provided configuration using Arch Linux

**Comment by fengwz17** [comment]
Thanks for all of the replies! I used "apt-get install" to install the required package and it works 👍
