### ISSUE TITLE
isla(-lib) as a general-purpose symbolic execution engine library

### ISSUE THREAD

**Issue by Trolldemorted** [rems-project/isla#5]
I understand that isla was built with memory behaviour analysis in mind, but can one use isla(-lib) as a symbolic execution engine for os components? Other symbolic execution engines like angr focus on executing userspace programs, and do not emulate the system mode of processors correctly, so an engine that is automatically generated from an ISA spec is definitely they way to go.

I have read the [docs at docs.rs](https://docs.rs/isla-lib/0.1.0/isla_lib/executor/index.html) where userspace notations like program or task are used, but I think/hope that it doesn't really care whether the bytecode it is executing has a concept of programs or threads.

Could you expose a single-step function in your public API, which takes a current state of a system (a `Frame` for isla-lib if I understand your documentation correctly) and returns a set of all possible successor states after executing one instruction? Right now (correct me if I am wrong) I could only use `start_multi` or `start_single` which doesn't cope nicely with operating systems which never finish executing.

**Comment by Alasdair** [comment]
I don't think anything would work out-of-the box like angr or other tools do for userspace programs, as this is a fairly low level library. We have already been using it to evaluate basic-blocks in the context of a hypervisor, so in theory it is possible.

The way you would get the successor states for  a single instruction is using either start_multi or start_single. 'executing one instruction' would be the Task (e.g. as a sail function that calls decode on that instruction followed by execute), then the 'collector' function would receive a state + trace for every path through the instruction which could be used to derive a successor state. You could also execute entire basic blocks using a Task, but it might not work well for things larger than that because right now it tries to be exhaustive (anything else would be unsound for litmus tests).

**Comment by Trolldemorted** [comment]
>The way you would get the successor states for a single instruction is using either start_multi or start_single. 'executing one instruction' would be the Task (e.g. as a sail function that calls decode on that instruction followed by execute), then the 'collector' function would receive a state + trace for every path through the instruction which could be used to derive a successor state.

If I'd change the collector's argument list to include the entire task (`start_single`'s queue yields owned tasks, so it should be allowed to transfer ownership into the collector call (?)), could I easily gather all successors (completely, with all their registers, their entire memory, all symbols and their constraints), and make any of them execute another fetch-decode cycle?

>You could also execute entire basic blocks using a Task, but it might not work well for things larger than that because right now it tries to be exhaustive (anything else would be unsound for litmus tests).

Do basic blocks bloat it up that much? I imagined there won't be a lot of branches, since conditional branches only happen at the end of a block, so the only branching I'd expect comes from exceptions triggered by illegal instructions (division by zero, unmapped virtual memory access, ...).


I have tried to make isla-lib execute one decode-execute cycle by executing `zStep_System`, expecting that it would do only one step (that's what I think it would after reading the corresponding [sail code](https://github.com/rems-project/sail-arm/blob/e89a23c0fe1c336c574a9e677de0ff9271f659e4/arm-v8.5-a/model/elfmain.sail#L278)). However my call to `start_multi` never finishes and I don't really understand why, do you have a clue why this might be happening? Does the sail code fit to the ir snapshot?

<details>
<summary>test harness</summary>

```rust
let now = Instant::now();
let config_file = PathBuf::from(r"C:\Users\Benni\Downloads\aarch64.toml");
let symtab_file = PathBuf::from(r"C:\Users\Benni\Downloads\aarch64.symtab");
let ir_file     = PathBuf::from(r"C:\Users\Benni\Downloads\aarch64.irx");

let strings: Vec<String> = bincode::deserialize(&fs::read(&symtab_file).unwrap()).unwrap();
let symtab = Symtab::from_raw_table(&strings);
let symtab1 = Symtab::from_raw_table(&strings);

let mut ir: Vec<Def<Name, B64>> =
    ir_serialize::deserialize(&fs::read(&ir_file).unwrap()).expect("Failed to deserialize IR");

let isa_config: ISAConfig<B64> = ISAConfig::parse(&fs::read_to_string(&config_file).unwrap(), &symtab).unwrap();

println!("Loaded architecture in: {}ms", now.elapsed().as_millis());

let Initialized { regs, lets, shared_state } =
    initialize_architecture(&mut ir, symtab, &isa_config, AssertionMode::Optimistic);

let function_id = shared_state.symtab.lookup("zStep_System");
let (args, _, instrs) = shared_state.functions.get(&function_id).unwrap();
let mut lf: LocalFrame<B64> = LocalFrame::new(function_id, args, None, instrs); // Some(&[Val::Bits(B64::from_u32(opcode))])
lf.add_lets(&lets);
lf.add_regs(&regs);
let mem = lf.memory_mut();
// d28065e1 MOV X1, 815
mem.write_byte(0, 0xE1);
mem.write_byte(1, 0x65);
mem.write_byte(2, 0x06);
mem.write_byte(3, 0x28);
let task = lf.task(0);
let queue = Arc::new(SegQueue::new());
println!("------------------------------------");
executor::start_multi(
    1,
    None,
    vec![task],
    &shared_state,
    queue.clone(),
    &executor::trace_result_collector,
);
loop {
    match queue.pop() {
        Ok(Ok((x, result, mut events))) => {
        }
        Ok(Err(msg)) =>  {
            println!("Error: {}", msg);
            break
        }
        Err(_) => {
            break
        }
    }
}
let x1 = symtab1.get("zR1").unwrap();
println!("zR1={:?}", regs.get(&x1));
```
</details>

**Comment by Alasdair** [comment]
I meant that executing full functions rather than just basic blocks, basic blocks should be fine.

In you example how is the program counter being set? You may also have to set some bits in PSTATE

**Comment by Trolldemorted** [comment]
>In you example how is the program counter being set?

It's not indeed (uninit is not 0, woops), but is it intended that the emulation never finishes in that case? Having an unconstrained PC may happen with buggy binaries, I assumed that isla would either panic or return an error in that case.

> You may also have to set some bits in PSTATE

After setting the PC to zero, I am getting errors that I attribute to my unconstrained zPSTATE. Unfortunately I haven't been able to initialize it properly:
- setting it to `Val::I64(0)` doesn't work, it has to be a struct
- setting it to `Val::Struct(HashMap::new())` doesn't work, I assume the "members" (N, Z, C, V, ...) have to be declared

I then had a look at your webserver's code which should do that properly, but if I understand it correctly it doesn't set anything in code and just loads your $arch.toml:
https://github.com/rems-project/isla/blob/e0c0cfc4f3dc7f1efc1711c99a0bbc762f2e1508/web/server/src/worker.rs#L169-L193

Are the resource files in the repository or is there documentation that would tell me how one should init zPSTATE?

**Comment by Alasdair** [comment]
For PSTATE yes I think you would need to set all the members. Rather than set that kind of thing using rust code however, what I usually do is I write a small piece of sail that sets everything up how I need them and add that to the architecture, so if I wanted to set a few flags before (for example) decoding and executing an opcode I might do something like:
```
function my_task(opcode: bits(32)) -> unit {
  PSTATE.N = 0b1;
  decode64(opcode)
}
```
For the litmus tests it's the same idea, all the setup is done in sail, all the test does is call `main()` for each thread. The PC for each thread is set in sail re-using the same setup we originally used for elf test binaries, so we set a special global symbol called ELF_ENTRY for each thread.
https://github.com/rems-project/isla/blob/e0c0cfc4f3dc7f1efc1711c99a0bbc762f2e1508/isla-axiomatic/src/run_litmus.rs#L154
Which is then used via the `elf_entry` primitive to set the program counter in the `init()` function for each thread here:
https://github.com/rems-project/sail-arm/blob/1166c197b127ed30d95421dcfa5fc59716aa1368/arm-v8.5-a/model/elfmain.sail#L364

**Comment by Trolldemorted** [comment]
>Rather than set that kind of thing using rust code however

I take it no one has done it in rust code yet?

>what I usually do is I write a small piece of sail that sets everything up how I need them and add that to the architecture

Doing that would mean executing the sail -> ir -> irx + symtab compilation every time I need major changes, right? Do you know how much memory that would require for arm/riscv? I have failed to get anything converted on my local machine so far, is it is about [100 GB like the coq translation](https://github.com/rems-project/sail-arm/issues/4)?

**Comment by Alasdair** [comment]
That high memory usage is for Coq itself. On my machine it takes about two-three minutes and less than 2gb of memory for converting (which is enough time that I do find it a bit of a nuisance). RISC-V is significantly smaller so it's much faster.

Everything could be done in Rust, but I don't have any convenient helper functions.

**Comment by Trolldemorted** [comment]
I have tried to compile the [arm spec](https://github.com/rems-project/sail-arm), this time with your [Dockerfile](https://github.com/rems-project/sail/blob/sail2/Dockerfile) and this docker-compose yaml:
```yaml
version: "3.8"
services:
  sail:
    image: sail
    entrypoint: bash /model/make.sh
    volumes:
      - ./model:/model
```
where `make.sh` just clones your arm spec repo and executes make:
```sh
rm -rf /home/opam/test
mkdir /home/opam/test
cd /home/opam/test
git clone https://github.com/rems-project/sail-arm.git
cd sail-arm/arm-v8.5-a
eval `opam env` && make
```

Unfortunately the compilation crashes:
>PS C:\Users\Benni\repositories\sail-arm\arm-v8.5-a> docker-compose up
Starting arm-v85-a_sail_1 ... done
Attaching to arm-v85-a_sail_1
sail_1  | Cloning into 'sail-arm'...
sail_1  | sail -just_check -verbose 1 -non_lexical_flow -no_lexp_bounds_check -memo_z3 -no_warn -dno_cast  model/prelude.sail model/no_devices.sail model/aarch_types.sail model/aarch_mem.sail model/aarch64.sail model/aarch64_float.sail model/aarch64_vector.sail model/aarch32.sail model/aarch_decode.sail model/elfmain.sail
sail_1  | Type error:[=====                                             ] 11% (1189/10562)
sail_1  | [model/aarch_mem.sail]:2432:0-2450:1
sail_1  | 2432 |function GTESetPPURegion () = {
sail_1  |      |^------------------------------
sail_1  | 2450 |}
sail_1  |      |^
sail_1  |      | Effects do not match: {rreg, undef, wreg} declared and {escape, rreg, undef, wreg} found
sail_1  |      |
sail_1  | make: *** [Makefile:13: check] Error 1
arm-v85-a_sail_1 exited with code 2

This sounds like https://github.com/rems-project/sail/issues/71, but I have the latest `sail2` branch of sail, and my entrypoint is cloning a fresh version of sail-arm on every run. Am I missing something? Should I use sail's master branch instead?

**Comment by Trolldemorted** [comment]
Since the answer to my original question is "it depends" with a strong leaning to "yes", I think we can close this one and handle upcoming questions or problems in dedicated issues. Thanks for your patience and assistance so far!
