### ISSUE TITLE
isla-sail build broken: Unbound value Initial_check.opt_undefined_gen

### ISSUE THREAD

**Issue by mmcloughlin** [rems-project/isla#74]
When attempting to build `isla-sail` I get the error:

```
File "sail_plugin_isla.ml", line 362, characters 2-33:
362 |   Initial_check.opt_undefined_gen := true;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Initial_check.opt_undefined_gen
```

This error occurs in the Github actions build as well:

https://github.com/rems-project/isla/actions/runs/7106561278/job/19346249334

The problem appears to be a change in sail not ISLA, specifically I think this commit:

https://github.com/rems-project/sail/commit/ff2647a35c9e65df38d7e8981d54bb64de443c95

Rolling back sail repository to prior to this commit fixed the issue.

**Comment by Alasdair** [comment]
Should be fixed now

**Comment by mmcloughlin** [comment]
Oh awesome, thank you!
