### ISSUE TITLE
How to handle LSL/LSR?

### ISSUE THREAD

**Issue by dc-mak** [rems-project/isla#8]
https://github.com/rems-project/isla/blob/aaee6da0a7ddfa83e14014045128188fc86f770b/isla-lib/src/error.rs#L39-L41

Specifically, LSL/LSR (register, example opcode: 9ac9242a) hits this bit of code:

https://github.com/rems-project/isla/blob/fc58b589a5d3fb6100e0ff5be63f0b2aa6f585cb/isla-lib/src/primop.rs#L585

This isn't blocking me; though it would be good for peace of mind to _somehow_ know that the instructions I'm skipping over (during a dataflow analysis in read-dwarf) are irrelevant.

Is this a "problem" with the ASL definitions?

**Comment by bacam** [comment]
The SMT bitvector theory doesn't support variable size bitvectors so it needs to be fixed up.  We already do this for Isabelle and once I remind myself of how that works I'll apply it to the IR version too.

**Comment by bacam** [comment]
I've pushed the versions of `LCL_C` and friends that we use in newer models to the symbolic branch of `sail-arm`.  That works for me with `isla-footprint`, but let me know if you still have problems with read-dwarf.  (In principle we could also solve this using the monomorphisation rewrites, but sail-arm has its own version of the prelude that doesn't play nicely with them.)

**Comment by dc-mak** [comment]
For my understanding, could you explain how [the change](https://github.com/rems-project/sail-arm/commit/803f806e404df36fe72965b3602c67beeb51350b#diff-82c03549346b694e3a9eda7a3c7bb450) gets around the problem of symbolic bitvector length?

**Comment by bacam** [comment]
The original versions define shifts by extending the input and selecting the desired bits.  It's the expanded bitvector that has a symbolic length.  The change replaces them with native shift operations, removing the expanded bitvectors entirely.

**Comment by dc-mak** [comment]
So it's ok to shift a fixed-length bit-vector by a symbolic amount left or right?

**Comment by bacam** [comment]
Yes, shifting in the bit-vector theory is defined as a family of functions on bit-vectors of the same length, so you can give a variable as the shift (unlike, I only just realised, `extract`, which only allows fixed indices).
