### ISSUE TITLE
Isla-footprint RISC-V 

### ISSUE THREAD

**Issue by neeluk7** [rems-project/isla#82]
Hello, 

I am trying to use the Isla-footprint tool to generate traces for RISC-V instructions but so far I have not been successful. I get an error for sail_barrier being an unknown event. (See image attached) 

![Screenshot 2024-09-30 at 14 05 07](https://github.com/user-attachments/assets/e05fe6df-603a-481a-b499-bcec251b6e13)

I assumed that it is because of outdated Isla IR snapshots, so I tried to regenerate them using Isla-sail. If that is not the case, please let me know if you have any idea why I am getting this error. 

For regenerating the snapshots, I followed the following advice from the README of this repo: 

"To generate this IR in the correct format a tool is available in the isla-sail directory. Building this requires various arcane OCaml incantations, but mostly one can follow the Sail install guide [here](https://github.com/rems-project/sail/blob/sail2/INSTALL.md), followed by the instructions [here](https://github.com/rems-project/isla/blob/master/isla-sail/README.md). It will only work with the latest HEAD of the sail2branch in the Sail repository." 

So the sail I use is from the sail2 branch. But running the Isla-sail tool for all the sail files in the RISC-V model throws the following error: 

![Screenshot 2024-09-30 at 14 05 35](https://github.com/user-attachments/assets/38caf4b8-2ef8-4fd1-bdbc-41cce7d99d8e)

If you could point me to where I might be going wrong, I will highly appreciate that. 

Thanks in advance. 
Regards, 
Neelu

**Comment by bacam** [comment]
I think you've just put the source files in the wrong order.  I can build it with the following change to the `Makefile` in sail-riscv:
```
--- a/Makefile
+++ b/Makefile
@@ -193,6 +193,8 @@ endif
 RISCV_EXTRAS_LEM_FILES = riscv_extras.lem mem_metadata.lem riscv_extras_fdext.lem
 RISCV_EXTRAS_LEM = $(addprefix handwritten_support/,$(RISCV_EXTRAS_LEM_FILES))
 
+ISLA_SAIL=isla-sail
+
 .PHONY:
 
 all: c_emulator/riscv_sim_$(ARCH)
@@ -214,6 +216,9 @@ sail_doc/riscv_$(ARCH).json: $(SAIL_SRCS) model/main.sail
 riscv.smt_model: $(SAIL_SRCS)
        $(SAIL) -smt_serialize $(SAIL_FLAGS) $(SAIL_SRCS) -o riscv
 
+riscv64.ir: $(SAIL_SRCS) model/main.sail
+       $(ISLA_SAIL) $(ISLA_SAIL_FLAGS) $(SAIL_SRCS) model/main.sail -o riscv64
+
 cgen: $(SAIL_SRCS) model/main.sail
        $(SAIL) -cgen $(SAIL_FLAGS) $(SAIL_SRCS) model/main.sail

```

**Comment by neeluk7** [comment]
Hello, 

Thanks for your response. Indeed the order of the source files needed to be fixed. I am able to build the IR now. 

But even then, generating instruction traces with Isla-footprint does not work and I get the following error: 

![Screenshot 2024-10-02 at 10 45 48](https://github.com/user-attachments/assets/93223654-c6eb-4ddb-b025-37cab961e1b3)
![Screenshot 2024-10-02 at 10 46 32](https://github.com/user-attachments/assets/85e82dc7-7fc0-4a56-aef0-dacdb5e1695e)

Even though val sys_pmp_count is defined in the sail source (and it's not really a function as Isla-footprint seems to be expecting). 

![Screenshot 2024-10-02 at 10 47 07](https://github.com/user-attachments/assets/7d2ff7ab-6c6e-4026-8be1-d11127d3de2d)


Can you please confirm if you see the same output or not? 
And if not, is it because of something missing in the command or should I be using a particular branch/commit from sail-riscv? 

I appreciate the help!

**Comment by bacam** [comment]
This is one of the configuration options for the RISC-V model, which they occasionally add to.  You can provide a value for it by adding a `sys_pmp_count` entry to the `const_primops` section at the bottom of the configuration file.  If you need some reasonable default values, look at those used for the C emulation in `c_emulator/riscv_platform_impl.c` in the `sail-riscv` repository.

**Comment by neeluk7** [comment]
Hello Brian, thanks for your reply. 

I tried adding it to the const_primops, and I get some type error now instead. 
![Screenshot 2024-10-02 at 13 45 15](https://github.com/user-attachments/assets/217f4874-8dda-427d-94ce-b496c0d01867)

It might be very trivial, 
but I just specified sys_pmp_count = 0 under the const_primops. It's similar to what I saw in the riscv_platform_impl.c. 

Is there a version of the config you could share that already has the necessary configurations specified?

**Comment by neeluk7** [comment]
Hello Brian, 

Thanks a lot for the help and prompt responses. The trace generation works now. 👍

**Comment by msuadOf** [comment]
> I think you've just put the source files in the wrong order. I can build it with the following change to the `Makefile` in sail-riscv:我认为你刚刚把源文件放错了顺序。我可以通过对 sail-riscv 中的 `Makefile` 进行以下修改来构建它：
> 
> ```
> --- a/Makefile
> +++ b/Makefile
> @@ -193,6 +193,8 @@ endif
>  RISCV_EXTRAS_LEM_FILES = riscv_extras.lem mem_metadata.lem riscv_extras_fdext.lem
>  RISCV_EXTRAS_LEM = $(addprefix handwritten_support/,$(RISCV_EXTRAS_LEM_FILES))
>  
> +ISLA_SAIL=isla-sail
> +
>  .PHONY:
>  
>  all: c_emulator/riscv_sim_$(ARCH)
> @@ -214,6 +216,9 @@ sail_doc/riscv_$(ARCH).json: $(SAIL_SRCS) model/main.sail
>  riscv.smt_model: $(SAIL_SRCS)
>         $(SAIL) -smt_serialize $(SAIL_FLAGS) $(SAIL_SRCS) -o riscv
>  
> +riscv64.ir: $(SAIL_SRCS) model/main.sail
> +       $(ISLA_SAIL) $(ISLA_SAIL_FLAGS) $(SAIL_SRCS) model/main.sail -o riscv64
> +
>  cgen: $(SAIL_SRCS) model/main.sail
>         $(SAIL) -cgen $(SAIL_FLAGS) $(SAIL_SRCS) model/main.sail
> ```

so, where is the `Makefile`? Could you show how to find it?
```bash
> find sail-riscv -name Makefile
sail-riscv/dependencies/softfloat/berkeley-softfloat-3/build/Linux-386-GCC/Makefile
sail-riscv/dependencies/softfloat/berkeley-softfloat-3/build/Linux-386-SSE2-GCC/Makefile
sail-riscv/dependencies/softfloat/berkeley-softfloat-3/build/Linux-ARM-VFPv2-GCC/Makefile
sail-riscv/dependencies/softfloat/berkeley-softfloat-3/build/Linux-RISCV64-GCC/Makefile
sail-riscv/dependencies/softfloat/berkeley-softfloat-3/build/Linux-x86_64-GCC/Makefile
sail-riscv/dependencies/softfloat/berkeley-softfloat-3/build/Win32-MinGW/Makefile
sail-riscv/dependencies/softfloat/berkeley-softfloat-3/build/Win32-SSE2-MinGW/Makefile
sail-riscv/dependencies/softfloat/berkeley-softfloat-3/build/Win64-MinGW-w64/Makefile
sail-riscv/dependencies/softfloat/berkeley-softfloat-3/build/template-FAST_INT64/Makefile
sail-riscv/dependencies/softfloat/berkeley-softfloat-3/build/template-not-FAST_INT64/Makefile
sail-riscv/doc/figs/Makefile
sail-riscv/os-boot/linux/Makefile
```

**Comment by neeluk7** [comment]
Hey, 

So the build system has changed and now there's model/CMakeLists.txt, what you want is the correct order of the sail source files: 

`message("The value of sail_srcs is: ${sail_srcs}")` 

Adding something like above in the model/CMakeLists.txt should help (for example, in line 218 in the current main) 

Then it will print the sail source files in the correct order, 

Then you can use that as args when running isla-sail   
Hope it helps.

**Comment by msuadOf** [comment]
> ，

Hello, can you give me your riscv64.ir? I tried to gennerate the IR, but everything goes bad...

**Comment by neeluk7** [comment]
Hey, 

I have one here you can use: 
https://github.com/neeluk7/sailor_artifact/blob/main/configs/riscv64-9454e6e8-IR-updated-init.ir 

It's for the commit id of sail-riscv mentioned in the file name, with small changes to the init that also reflect better the init in more recent versions of sail-riscv ... Here's the patch to sail-riscv that I applied for generating the above IR, for your reference: 
https://github.com/neeluk7/sailor_artifact/blob/main/patches/sail-riscv.patch

**Comment by msuadOf** [comment]
Thanks a lot for your work! What is your sail version? I want to recompile the IR.

**Comment by neeluk7** [comment]
Sorry for the delayed response! 
The last time I recompiled the IR, I was using Sail 0.18.0 (HEAD @ 5152e254bad70381c943eac5417affc08082e889). 

Hope it helps. 
You might also try checking out the actions in this repo, that might help figure out the compatible versions too.
